# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
NULL

pmn_mdfft_arma <- function(nnt, pp, nn_vec, l_vec, cn_vec) {
    .Call(`_PoissonMultinomial_pmn_mdfft_arma`, nnt, pp, nn_vec, l_vec, cn_vec)
}

rpmd_arma <- function(pp) {
    .Call(`_PoissonMultinomial_rpmd_arma`, pp)
}

pmd_simulation_singlepoint <- function(pp, x_vec, t) {
    .Call(`_PoissonMultinomial_pmd_simulation_singlepoint`, pp, x_vec, t)
}

pmd_simulation_allpoints <- function(pp, nnt, l_vec, cn_vec, t) {
    .Call(`_PoissonMultinomial_pmd_simulation_allpoints`, pp, nnt, l_vec, cn_vec, t)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_PoissonMultinomial_RcppExport_registerCCallable', PACKAGE = 'PoissonMultinomial')
})
